### ISSUE TITLE
Dataset could not be updated without updating the metadata form

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#2203] opened 2021-07-02 19:48 UTC
**Describe the bug**

User was unable to update a dataset (https://openneuro.org/datasets/ds000247) via the web (Chrome and Firefox) or CLI. Discovered that upload events were triggering something related to the metadata form, which was added well after ds000247 was initially uploaded and released. Updating a few fields, they were then able to make the desired updates.

I suspect this may be related to constraints we've put on the defacing options.

cc @soichih @guiomar who may be able to provide more details

**Comment by guiomar** [comment] 2021-07-06 17:50
Thanks for all your help @effigies !!

Indeed @soichih discovered that the possible cause that prevented the upload was related to the new metadata options, so after we filled in a few fields and marked that mris were defaced, it allowed us to load the data (thanks once more Soichi!).

If you need I provide some more details just let me know. 

I also found another possible minor bug? My new dataset has different session names, so both were kept when I uploaded the data without deleting the old one (this was expected). Then, I preceded to delete the old sessions manually, but even though they apparently disappeared, when I refreshed the page the deleted old sessions reappeared again. It's not a problem, because I just deleted the whole subject, and it loaded it again. And it worked. But in case someone else reported this behavior and you want to have a look.

**Comment by david-nishi** [comment] 2021-07-27 23:37
Thanks for the info @guiomar and @soichih. I believe I've found browser-side bug preventing uploads (fix in #2268), and am working on reproducing the CLI issue. Does the following look like what you were getting from that?
```
Starting a new upload (31b50fb4) to dataset: 'ds000247’
ds000247 [========--------------------------------] 18% | ETA: 2s | 18/96Retrying upload for y
Warning: "sub-0003/ses-01/meg/sub-0003_ses-01_task-rest_run-01_meg.ds/BadChannels" read zero bytes - check that this file is readable and try again
Warning: "sub-0003/ses-01/meg/sub-0003_ses-01_task-rest_run-01_meg.ds/bad.segments" read zero bytes - check that this file is readable and try again
Retrying upload for sub-0002/ses-01/meg/sub-0002_ses-01_task-rest_run-01_meg.ds/sub-0002_ses-01_task-rest_run-01_meg.meg4: ReferenceError: Body already used
Retrying upload for sub-0002/ses-01/meg/sub-0002_ses-01_task-rest_run-01_meg.ds/sub-0002_ses-01_task-rest_run-01_meg.meg4: ReferenceError: Body already used
Retrying upload for sub-0002/ses-01/meg/sub-0002_ses-01_task-rest_run-01_meg.ds/sub-0002_ses-01_task-rest_run-01_meg.meg4: ReferenceError: Body already used
Retrying upload for sub-0002/ses-01/meg/sub-0002_ses-01_task-rest_run-01_meg.ds/sub-0002_ses-01_task-rest_run-01_meg.meg4: Error: Failed to upload file after 5 attempts - "http://localhost:9876/uploads/1/ds001033/31b50fb4/sub-0002:ses-01:meg:sub-0002_ses-01_task-rest_run-01_meg.ds:sub-0002_ses-01_task-rest_run-01_meg.meg4"
Retrying upload for sub-0002/ses-01/meg/sub-0002_ses-01_task-rest_run-01_meg.ds/sub-0002_ses-01_task-rest_run-01_meg.meg4: ReferenceError: Body already used
Retrying upload for sub-0002/ses-01/meg/sub-0002_ses-01_task-rest_run-01_meg.ds/sub-0002_ses-01_task-rest_run-01_meg.meg4: ReferenceError: Body already used
Retrying upload for sub-0002/ses-01/meg/sub-0002_ses-01_task-rest_run-01_meg.ds/sub-0002_ses-01_task-rest_run-01_meg.meg4: ReferenceError: Body already used
Error: socket hang up
    at connResetException (node:internal/errors:642:14)
    at Socket.socketOnEnd (node:_http_client:496:23)
    at Socket.emit (node:events:381:22)
    at Socket.emit (node:domain:470:12)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'ECONNRESET'
}
```

**Comment by tommydino93** [comment] 2021-12-01 10:37
Hi All,
I believe I am facing a similar issue. When uploading the dataset via the CLI I get:
```
Starting a new upload (7ae51843) to dataset: 'ds003939'
ds003939 [----------------------------------------] 0% | ETA: 0s | 0/5735Retrying upload for derivatives/N4_bias_field_corrected/sub-000/ses-20110101/anat/sub-000_ses-20110101_desc-a 
Retrying upload for derivatives/N4_bias_field_corrected/sub-000/ses-20110101/anat/sub-000_ses-20110101_desc-angio_N4bfc_mask.nii.gz: Error: Failed to upload file after 8 attempts - ""
Retrying upload for derivatives/N4_bias_field_corrected/sub-002/ses-20110127/anat/sub-002_ses-20110127_desc-angio_N4bfc_mask.json: 
Retrying upload for derivatives/N4_bias_field_corrected/sub-002/ses-20110127/anat/sub-002_ses-20110127_desc-angio_N4bfc_mask.json: Error: Failed to upload file after 15 attempts - "h"
Retrying upload for code/github_repository: 
Retrying upload for derivatives/N4_bias_field_corrected/sub-000/ses-20110101/anat/sub-000_ses-20110101_desc-angio_N4bfc_brain_mask.json: 
Retrying upload for derivatives/N4_bias_field_corrected/sub-000/ses-20110101/anat/sub-000_ses-20110101_desc-angio_N4bfc_brain_mask.json: Error: Failed to upload file after 5 attempts"
Retrying upload for code/github_repository: ReferenceError: Body already used
Retrying upload for code/github_repository: ReferenceError: Body already used
Retrying upload for code/github_repository: ReferenceError: Body already used
Retrying upload for code/github_repository: Error: Failed to upload file after 5 attempts - "https://openneuro.org/uploads/3/ds003939/7ae51843/code:github_repository"
Retrying upload for code/github_repository: ReferenceError: Body already used
Retrying upload for code/github_repository: ReferenceError: Body already used
...
```
while if I try to upload the dataset vie the web interface, I get:
`Too many failed attempts for 'sub-491/ses-20151124/anat/sub-491_ses-20151124_T1w.nii.gz, sub-491/ses-20151124/anat/sub-491_ses-20151124_angio.nii.gz, sub-492/ses-20151228/anat/sub-492_ses-20151228_T1w.nii.gz, sub-490/ses-20151206/anat/sub-490_ses-20151206_angio.nii.gz
...
...long similar list
`

What could I try?
Thank you very much in advance :)

**Comment by nellh** [comment] 2023-09-18 16:44
This issue should be fixed in the current release.

**Closed as completed by nellh** 2023-09-18 16:44 UTC
Labels: bug
