### ISSUE TITLE
Uncaught Error: All file URLs failed

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#745] opened 2018-07-11 23:08 UTC
When trying to download https://datalad-production.sqm.io/datasets/ds001132/versions/00002

```
sw.js:24 Uncaught Error: All file URLs failed.
    at e (sw.js:24)
    at d.t.zipFiles.o._read (sw.js:24)
    at d.read (sw.js:24)
    at w (sw.js:24)
    at sw.js:24
    at d.run (sw.js:24)
    at s (sw.js:24)
```

**Comment by nellh** [comment] 2018-07-11 23:32
This should be a duplicate of #746 - caused by a fix for another issue from today. `[] != false` in Javascript. I'll deploy the fix to the datalad staging site after the build on Circle finishes.

**Comment by nellh** [comment] 2018-07-31 18:20
This required a cache clear post migration but we shouldn't be seeing this on production, the cache clear was done after the migration completed.

**Closed as completed by nellh** 2018-07-31 18:20 UTC
Labels: bug
