### ISSUE TITLE
Large upload over slow connection

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1455] opened 2020-01-10 16:53 UTC
A user was having trouble uploading over a slow connection, and I suggested they try the CLI. That produced the following error:

```
Transferring "sub-01/ses-04/func/sub-01_ses-04_task-HcpRelational_acq-pa_bold.nii.gz" - 58% complete (432.2 MB remaining)
(node:4128) UnhandledPromiseRejectionWarning: Error: Network error: Unexpected token < in JSON at position 0
    at new ApolloError (/usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:92:26)
    at Object.error (/usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:1330:28)
    at notifySubscription (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:240:7)
    at /usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:1107:37
    at Set.forEach (<anonymous>)
    at Object.error (/usr/local/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:1106:21)
    at notifySubscription (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/usr/local/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:179:3)
(node:4128) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:4128) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

REF: Freshdesk ticket 544

**Comment by ckrountree** [comment] 2020-01-13 20:26
Duplicate of #1299

**Closed as completed by ckrountree** 2020-01-13 20:26 UTC
Labels: openneuro-cli
