### ISSUE TITLE
CLI - Error: Cannot find module 'graphql-tag'

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1549] opened 2020-02-20 19:36 UTC
reported by users affecting the `openneuro login` command

I have attached the error message they are seeing

They have tried using the patch release from yesterday (v3.12.8) are on Ubuntu 18.04.2 LTS using node: v13.6.0 (have also tried node 10 and 12 too)

```
/usr/lib/node_modules/openneuro-cli/src/snapshots.js:1
Error: Cannot find module 'graphql-tag'
Require stack:
- /usr/lib/node_modules/openneuro-cli/src/snapshots.js
- /usr/lib/node_modules/openneuro-cli/src/actions.js
- /usr/lib/node_modules/openneuro-cli/src/cli.js
- /usr/lib/node_modules/openneuro-cli/src/index.js
    at Object.<anonymous> (/usr/lib/node_modules/openneuro-cli/src/snapshots.js:1) {   code: 'MODULE_NOT_FOUND',   requireStack: [     '/usr/lib/node_modules/openneuro-cli/src/snapshots.js',     '/usr/lib/node_modules/openneuro-cli/src/actions.js',     '/usr/lib/node_modules/openneuro-cli/src/cli.js',     '/usr/lib/node_modules/openneuro-cli/src/index.js'   ] }
```

**Comment by nellh** [comment] 2020-02-20 19:57
This package is missing because it was previously a dependency of other dependencies and happened to be available, but isn't required by openneuro-cli or openneuro-client. We have some linting to catch this error but it isn't working when another unrelated openneuro monorepo package has installed the dependency. #1551 will catch this in the future.

For now we'll publish 3.12.9 with the correct package.json dependencies and you can work around it for 3.12.8 with `yarn add graphql-tag` or `npm install graphql-tag`.

**Comment by nellh** [comment] 2020-02-20 20:16
3.12.9 has been released with this fix.

**Closed as completed by nellh** 2020-02-20 20:16 UTC

**Comment by weiyongxu** [comment] 2020-02-20 21:36
> 3.12.9 has been released with this fix.
Hi,

Thanks for fixing it! I got another error with 3.12.9:

/usr/local/lib/node_modules/openneuro-cli/node_modules/openneuro-client/src/datasetGenerator.js:8
export default async function* datasetGenerator(client, query = getDatasets) {

SyntaxError: Unexpected token *
    at Object.Module._extensions..js (module.js:663:10)

**Comment by nellh** [comment] 2020-02-20 21:44
> > 3.12.9 has been released with this fix.
> > Hi,
> 
> Thanks for fixing it! I got another error with 3.12.9:
> 
> /usr/local/lib/node_modules/openneuro-cli/node_modules/openneuro-client/src/datasetGenerator.js:8
> export default async function* datasetGenerator(client, query = getDatasets) {
> 
> SyntaxError: Unexpected token *
> at Object.Module._extensions..js (module.js:663:10)

This is caused by an out of date version of Node.js, can you try with Node 12?

**Comment by weiyongxu** [comment] 2020-02-20 22:07
> > > 3.12.9 has been released with this fix.
> > > Hi,
> > 
> > 
> > Thanks for fixing it! I got another error with 3.12.9:
> > /usr/local/lib/node_modules/openneuro-cli/node_modules/openneuro-client/src/datasetGenerator.js:8
> > export default async function* datasetGenerator(client, query = getDatasets) {
> > SyntaxError: Unexpected token *
> > at Object.Module._extensions..js (module.js:663:10)
> 
> This is caused by an out of date version of Node.js, can you try with Node 12?

The new version of Node works fine. Thanks!
