### ISSUE TITLE
Dataset name mismatch

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#846] opened 2018-08-18 07:01 UTC
On public dashboard (https://openneuro.org/public/datasets):
![image](https://user-images.githubusercontent.com/238759/44296755-d7a4ed80-a2c4-11e8-8edf-d5bd13547d9e.png)

On dataset landing page (https://openneuro.org/datasets/ds001454):
![image](https://user-images.githubusercontent.com/238759/44296760-ed1a1780-a2c4-11e8-9db6-744a54ceb40e.png)

**Comment by nellh** [comment] 2018-08-27 19:17
This is a duplicate of #693

**Closed as completed by nellh** 2018-08-27 19:17 UTC
Labels: bug
