### ISSUE TITLE
Fix datasets unavailable to download

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1235] opened 2019-08-12 18:33 UTC
Some datasets may have been missed by our auditing (https://github.com/OpenNeuroOrg/openneuro/issues/1115), appear they are still private, but publicly available - 
https://openneuro.org/datasets/ds002013/versions/1.0.0

**Comment by nellh** [comment] 2019-08-13 18:49
This was caused by #1155 - we should be able to fix this dataset following the 3.5.0 release tomorrow.

**Comment by ckrountree** [comment] 2019-08-19 21:24
This may also be blocked by #1241.

**Comment by nellh** [comment] 2019-08-20 22:18
This is fixed with the 3.5.2 release.

**Closed as completed** 2019-08-20 22:18 UTC
Labels: reported by external user, Maintenance
