### ISSUE TITLE
Fix error boundary on deleted datasets

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1260] opened 2019-08-22 18:44 UTC
Providing a message on a dataset whether it has been deleted or indeed an error (provided by the error boundary). This would notify the user that it is not the system (or them) that errored, but rather the dataset has been deleted. 

cc and credit - @effigies

**Comment by effigies** [comment] 2019-08-22 20:28
Duplicate of #1193.

**Closed as completed by effigies** 2019-08-22 20:28 UTC
