### ISSUE TITLE
Validation pending stuck on datasets

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1196] opened 2019-07-22 21:43 UTC
We are starting to see a higher rate of `validation pending` that is stuck on a number of datasets. Perhaps this is attributed to the loading errors?

**Comment by nellh** [comment] 2019-07-29 19:05
This should be fixed for any new changes to datasets but need to go back and rerun some pending validations still.

**Comment by nellh** [comment] 2019-07-29 22:44
This should now be run for the affected datasets, though we have a related issue documented in #1219 which is the cause of any which have not been validated.

**Closed as completed by nellh** 2019-07-29 22:44 UTC
Labels: bug
