### ISSUE TITLE
Delete incomplete datasets

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1195] opened 2019-07-18 19:42 UTC
Edit: This is a request to delete these datasets. The user declined to resume the uploads of large datasets for the sake of enabling the delete option.

----

A user attempted to upload a dataset via the CLI. On failure, the page was unusable. They did this twice before succeeding with another attempt.

One possibility that strikes me is that perhaps the CLI does not upload  `dataset_description.json` first, which I believe we adjusted the web frontend to do.

Is there a front-end approach for deleting these datasets at this point? I've asked the user to resume uploads on those, which might clear the way to deletion.

* https://openneuro.org/datasets/ds002044
* https://openneuro.org/datasets/ds002045
<img width="1166" alt="Screen Shot 2019-07-18 at 15 33 20" src="https://user-images.githubusercontent.com/83442/61486426-69075e80-a971-11e9-80c6-ce15e55fecd6.png">

**Comment by nellh** [comment] 2019-07-18 19:43
This is a duplicate of #1183

**Comment by effigies** [comment] 2019-07-18 19:44
Ah, thanks.

**Comment by effigies** [comment] 2019-07-23 17:49
Reopening. It's not urgent to delete these, but I figured I'd throw this into the to-do list.

**Comment by nellh** [comment] 2019-08-16 18:19
It's now possible for site admins or dataset admins to delete these after we fixed other issues with draft state error handling.

**Closed as completed by nellh** 2019-08-16 18:19 UTC
Labels: Maintenance
