### ISSUE TITLE
Google reported Mobile Usability issues

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1278] opened 2019-09-10 17:01 UTC
This ticket captures the various google search console errors flagged...

**Comment by nellh** [comment] 2019-09-10 17:04
This is a duplicate of #1268 - we should record any URLs affected there.

**Closed as completed by nellh** 2019-09-10 17:04 UTC

**Comment by ckrountree** [comment] 2019-09-10 17:06
**ds000244** - (9/8 detected)

- [ ] content wider than screen
- [ ] clickable elements too close together
