### ISSUE TITLE
ds002837 - portions are not accessible (403, Permission denied)

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroOrg/openneuro#2128] opened 2021-05-12 20:22 UTC
some files are ok

```shell
$> git annex get nih_toolbox_data.csv
get nih_toolbox_data.csv (from s3-PUBLIC...) (checksum...) ok
(recording state in git...)
```

but attempt at getting this one from under derivatives/ - not 
```
$> git annex get derivatives/sub-10/func/sub-10_task-500daysofsummer_bold_blur_censor.nii.gz
get derivatives/sub-10/func/sub-10_task-500daysofsummer_bold_blur_censor.nii.gz (from s3-PUBLIC...) 
  download failed: Forbidden

  download failed: Forbidden
(Delaying 1s before retrying....)

  download failed: Forbidden

  download failed: Forbidden
(Delaying 2s before retrying....)

  download failed: Forbidden

  download failed: Forbidden

  Unable to access these remotes: s3-PUBLIC

  Maybe add some of these git remotes (git remote add ...):
        dabe7853-a71e-4858-bf90-0c4917c7a601 -- root@openneuro-prod-dataset-worker-10:/datalad/ds002837

  (Note that these git remotes have annex-ignore set: origin)
failed
git-annex: get: 1 failed
```
and indeed it is there but not allowed (see 403 by the end if it tries to access the file via http url)
```shell
$> datalad ls -L s3://openneuro.org/ds002837/derivatives/sub-10/func/sub-10_task-500daysofsummer_bold_blur_censor.nii.gz
Connecting to bucket: openneuro.org
[INFO   ] S3 session: Connecting to the bucket openneuro.org anonymously 
Bucket info:
  Versioning: S3ResponseError: 403 Forbidden
     Website: S3ResponseError: 403 Forbidden
         ACL: <Policy: openneurocommon (owner) = FULL_CONTROL, http://acs.amazonaws.com/groups/global/AllUsers = READ, rblair2 = FULL_CONTROL, http://acs.amazonaws.com/groups/global/AllUsers = READ_ACP>
ds002837/derivatives/sub-10/func/sub-10_task-500daysofsummer_bold_blur_censor.nii.gz 2021-04-21T00:35:35.000Z 1531896573 ver:fsSF1XBxNfxSaxxa2MUnlpTM2lCQfDHL  acl:AccessDenied  http://openneuro.org.s3.amazonaws.com/ds002837/derivatives/sub-10/func/sub-10_task-500daysofsummer_bold_blur_censor.nii.gz?versionId=fsSF1XBxNfxSaxxa2MUnlpTM2lCQfDHL [E: 403]
```

**Comment by franklin-feingold** [comment] 2021-05-12 20:37
@rwblair the AWS ACL issue

**Comment by effigies** [comment] 2021-05-12 20:40
Is this an AWS bug, or is there something in our process causing this?

**Comment by franklin-feingold** [comment] 2021-05-12 21:38
it was something in our process that caused it - we have since resolved it (couldn't identify the exact PR resolving it). this dataset is one of the legacy ones that was affected by the previous issue

**Comment by effigies** [comment] 2021-05-12 21:49
Is it feasible to do a global fix, or do we have to fix them as we/others find them?

**Comment by franklin-feingold** [comment] 2021-05-12 21:56
@rwblair may have thoughts

**Comment by nellh** [comment] 2021-05-12 22:08
We have a script to fix ACLs globally, it takes a couple days to run for the entire bucket.

I'm not sure the cause is actually 100% fixed, it still seems that occasionally the request creating an S3 object succeeds but the ACL is not applied somehow.

**Comment by rwblair** [comment] 2021-05-13 17:33
I've run the ACL fix script on the ds002837. Looking at my bash history it looks like I have run the script on this particular dataset before, and that the files corrected by it are more recent modifications.

Seem to be a lot of delete markers with timestamps around the problematic version timestamp:
https://gist.github.com/rwblair/c27e3b37bc480b2f7fc53c8077e4b28e

**Comment by nellh** [comment] 2023-03-29 18:58
This case was fixed and we're moving away from using ACLs to enable public access shortly.

**Closed as completed by nellh** 2023-03-29 18:58 UTC
Labels: bug
