### ISSUE TITLE
Job results not available

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#857] opened 2018-08-28 18:28 UTC
https://openneuro.org/datasets/ds001205/versions/00002/results/openneuro.outputs%2Ff267ed5273788006fa14cac2a486ffcb%2F9ccc1158-908f-447e-a36e-2513476648bd%2Freports%2Fsub-001_task-MGT_run-04_bold.html
![image](https://user-images.githubusercontent.com/238759/44742660-477d5a00-aab5-11e8-82f0-93a136408756.png)

**Comment by nellh** [comment] 2018-08-28 18:35
This is a duplicate of #790

**Closed as completed by nellh** 2018-08-28 18:35 UTC
Labels: bug, prod server
