### ISSUE TITLE
Set expectations for downloads in Firefox

### ISSUE THREAD

**Issue by ckrountree** [OpenNeuroOrg/openneuro#1598] opened 2020-04-24 22:49 UTC
Mozilla needs to make some updates before Firefox will be a decent browser choice for downloads.  In the meantime, we should add a message to discourage users from downloading in Firefox.

**Comment by ckrountree** [comment] 2020-04-24 22:50
This issue is not the same but related to #1596.  @effigies This issue specifically affects ds002680 and ds002691.

**Comment by nellh** [comment] 2020-05-15 21:20
This looks like a duplicate of #1590

**Closed as completed by nellh** 2020-05-15 21:20 UTC
Labels: UI/UX
