### ISSUE TITLE
Add error boundary to My Dashboard - All

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1655] opened 2020-06-23 21:45 UTC
**Describe the bug**
Within `My Dashboard` for site administrators our right-hand side `filter` section suffers from GraphQL errors regularly. This affects the capability to view all datasets uploaded to OpenNeuro. This is important for user support and platform performance evaluations.

**To Reproduce**
1. Go to 'My Dashboard'
2. Click on 'Filter -> All'
3. See error - `GraphQL error: Internal Server Error GraphQL error: Internal Server Error
Please support us by documenting the issue with FreshDesk.`
FreshDesk support ticket text: `Error: GraphQL error: Internal Server ErrorGraphQL error: Internal Server Error`

**Expected behavior**
Listing all datasets uploaded to OpenNeuro.

**Desktop (please complete the following information):**
 - Browser [e.g. Chrome, Safari]: Chrome
 - Version [e.g. 22]: 83.0

**Comment by nellh** [comment] 2020-06-23 22:21
This is a duplicate of #1443 - the buggy error boundary responsible for #1443 catches this error and prevents the existing one from rendering the page properly. #1405 reverted, this correctly catches the issue for individual datasets and shows the metadata needed to track those datasets down.

**Closed as completed by nellh** 2020-06-23 22:21 UTC
