### ISSUE TITLE
Change policy on datasets

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1242] opened 2019-08-14 18:55 UTC
Currently, the policy states that a dataset will be made public 36 months after an analysis is performed. We do not support analysis performed within OpenNeuro. 

The policy can be changed to a private dataset is made public 36 months after the first snapshot is created. A snapshot provides a DOI so this is the rationale of why a snapshot is the trigger for beginning the countdown.

**Comment by nellh** [comment] 2019-09-04 23:33
- [x] FAQ update
- [ ] Uploader page update

**Comment by ckrountree** [comment] 2020-06-25 22:34
@david-nishi  This was addressed in #1576 which was released in 3.14.3.

**Comment by franklin-feingold** [comment] 2020-06-25 23:53
note: this doesn't appear on production - I'll submit a PR soon to resolve [those locations](https://github.com/OpenNeuroOrg/openneuro/issues/1242#issuecomment-528132010)

**Comment by ckrountree** [comment] 2020-06-26 18:12
@franklin-feingold double-checked.  This was accidentally added to release notes as a duplicate of #1521 (not #1242).  Reopening this one.

**Closed as completed** 2020-07-27 23:39 UTC
Labels: Released
