### ISSUE TITLE
unable to download snapshot on ds001430 v1.0.0

### ISSUE THREAD

**Issue by olgn** [OpenNeuroOrg/openneuro#902] opened 2018-09-13 17:55 UTC
console shows the following output (when logged in as admin and when not logged in):

```
zipEntry.js:292 Uncaught TypeError: Cannot read property 'length' of null
    at t (zipEntry.js:292)
    at y.e.zipFiles.o._read (zipEntry.js:292)
    at y.read (zipEntry.js:292)
    at R (zipEntry.js:292)
    at zipEntry.js:292
    at p.run (zipEntry.js:292)
    at d (zipEntry.js:292)
```

additional information: draft downloads just fine.

**Comment by nellh** [comment] 2018-09-13 18:01
This is the URLs missing. This dataset might have failed during the export to S3?

**Comment by ckrountree** [comment] 2018-10-31 18:50
duplicate of #935

**Closed as completed by ckrountree** 2018-10-31 18:50 UTC
Labels: bug
