### ISSUE TITLE
Resuming uploads does not work

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#751] opened 2018-07-12 02:07 UTC
Trying to resume upload of this dataset https://openneuro.dev.sqm.io/datasets/ds001117. Clicking on resume on dashboard or dataset page opens folder selection dialog, but does not start the upload process. There are no errors on the console.

The name of the dataset does not match the name of the uploaded folder.

**Comment by olgn** [comment] 2018-07-13 16:55
this appears to be a duplicate of #705.

**Closed as completed by olgn** 2018-07-13 16:55 UTC
Labels: bug, critical, dev server
