### ISSUE TITLE
[ENH] Revert to last version on openneuro.org

### ISSUE THREAD

**Issue by alexrockhill** [OpenNeuroOrg/openneuro#2777] opened 2023-02-16 17:19 UTC
### What would you like to see added?

It would be nice if you messed up editing your files and/or uploading new files if you could revert to the last snapshot and start anew with your draft. The motivating example for this is accidentally uploading the entire BIDS dataset within the original one as a sub-directory. If https://github.com/OpenNeuroOrg/openneuro/issues/2776 gets implemented this won't be as necessary but still seems like a nice feature to me.

### Do you have any interest in helping implement the feature?

Yes

**Comment by nellh** [comment] 2023-02-16 18:26
This is a duplicate of #2637

**Closed as completed by nellh** 2023-02-16 18:26 UTC
