### ISSUE TITLE
Chrome/Google login issues

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#380] opened 2018-01-31 19:31 UTC
See https://neurostars.org/t/events-files-unrecognised-by-openneuro/1249/9?u=chrisgorgolewski

**Comment by nellh** [comment] 2018-01-31 20:32
A guess for this, if you have an invalid refresh token in localStorage, it looks possible to get stuck rather than being logged out (which is the correct action to take if the refresh token request fails). Each page load tries to refresh the token, fails, doesn't log you out. Clearing local storage would temporarily fix it if this is the cause here.

**Comment by nellh** [comment] 2018-02-07 20:28
The proposed fix for this is updated on dev, failures during any part of the login for Google accounts will now log you out (clearing bad refresh tokens) and let you try again.

**Closed as completed** 2018-02-08 23:59 UTC
Labels: bug
