### ISSUE TITLE
Interrupted update of a file locks the dataset

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#985] opened 2018-10-27 16:36 UTC
Steps to reproduce (as described by a user):

1. Attempt to update a large file
2. Interrupt the upload
3. Dataset gets into the "You will have limited functionality on this dataset until it is completed. Please click resume to finish uploading." state
4. Clicking "Resume" allows users only to pick folders - not files.

Example: https://openneuro.org/datasets/ds001219

**Comment by nellh** [comment] 2018-10-27 16:47
This is a duplicate of #844

**Closed as completed** 2018-10-27 16:57 UTC
Labels: bug, reported by external user
