### ISSUE TITLE
RFC: Thresholds for .bidsignore files

### ISSUE THREAD

**Issue by effigies** [OpenNeuroOrg/openneuro#1199] opened 2019-07-23 14:21 UTC
The `.bidsignore` file exists to enable curators to specify files that are important to include in the dataset for completeness, but do not (yet) have a standardized way to represent the information. This can be abused to simply prevent the validator from doing its job, and allow a curator to upload an entirely non-BIDS dataset.

We have discussed (off of GitHub) the possibility of identifying a maximum number of ignored files, and @jasmainak suggested in https://github.com/bids-standard/bids-validator/issues/804#issuecomment-514010951 that a proportional threshold would be a good criterion. Another possibility is a proportional threshold for data in bytes, as opposed to file counts.

I think we have a couple obvious constraints:

1) Original OpenFMRI datasets should not be invalidated by whatever choice we make. These were curated by people strongly motivated to conform to BIDS and not simply to post data.
2) `derivatives/` and `sourcedata/` subdirectories should probably not count toward the numerator or denominator, as they are either sub-datasets or sheltered by current BIDS rules. Derivatives in particular can outweigh the primary dataset significantly.

We may want to consider an administrative override. A dataset might be flagged by whatever criteria we develop, but an admin should be able to look and see that `.bidsignore` is used as intended.

This is related to bids-standard/bids-validator#804.

cc @sappelhoff

**Comment by jasmainak** [comment] 2019-07-23 14:28
+1 for this! I would say that a threshold/criteria that works for most of the datasets currently on OpenNeuro might be a good one. One might have to go back and fix a few datasets such as ds001512 but I think it's worth the effort. We should assume good intent ... thus most datasets probably already conform and have been carefully curated.

**Comment by effigies** [comment] 2019-07-23 14:42
ds001512 has 4 excluded files per subject. I'm skeptical that we'll get a threshold that catches that that doesn't sweep up a lot of legitimate datasets.

**Comment by sappelhoff** [comment] 2019-07-23 14:47
I think the general idea is important and having a threshold based approach sounds sensible. To get concrete ideas, it might be helpful to program a pipeline, that applies a user-defined threshold method to all datasets on OpenNeuro, and returns how many would be invalidated (including an option `verbose` mode).

Then we can directly test suggestions by just plugging in the "user defined threshold method" and we could iterate towards a bounded optimum.

**Comment by ckrountree** [comment] 2019-12-04 19:25
Closing because duplicate of https://github.com/bids-standard/bids-validator/issues/844

**Closed as completed by ckrountree** 2019-12-04 19:25 UTC
Labels: idea
