### ISSUE TITLE
ORCID and Google log in

### ISSUE THREAD

**Issue by arnodelorme** [OpenNeuroOrg/openneuro#3004] opened 2024-02-29 19:21 UTC
### What went wrong?

I logged in with Google (arnodelorme@gmail.com) and linked my ORCID account (arno@ucsd.edu). All good. Then logged off and logged back in with ORCID. However, this was a different account, not the account that was linked with ORCID.

### Expected behavior

Now that the link exists between Google and ORCID, users should be allowed to log onto their account using either.

### Desktop

- OS:
- Browser:
- Version:

### Phone

- Device:
- OS:
- Browser:
- Version:

**Comment by effigies** [comment] 2024-02-29 19:27
Thanks @arnodelorme. We haven't yet merged accounts, but this is on our roadmap.

I think this is a duplicate of https://github.com/OpenNeuroOrg/openneuro/issues/180, but I'll leave it to @nellh  to determine if this goal is adequately represented in the issue list.

**Closed as not planned** 2024-11-05 17:36 UTC
Labels: feature
