### ISSUE TITLE
CLI upload/update error

### ISSUE THREAD

**Issue by franklin-feingold** [OpenNeuroOrg/openneuro#1324] opened 2019-10-14 22:40 UTC
user is reporting this error when using the CLI. The user was able to set up and login successfully. The user also validated his dataset using the web browser and it passed. The sure

This appears to be a potential permission issue. The files permissions are open to him (report below)
```
report: drwxr-xr-x 
```

here is the CLI attempt command line readout

```
Xystem：Linux version 4.15.0-60-generic (buildd@lgw01-amd64-030) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1))
Version of openneuro: 3.6.0
Command：openneuro upload --dataset ds001769 workingdir/studyforrest_denoise_v1.3.0
Report：Adding files to "ds001769"
(node:30174) ExperimentalWarning: The http2 module is an experimental API.
bids-validator@1.3.6

(node:30174) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'readdir' of undefined
    at getFilesFromFs (/usr/local/lib/node_modules/openneuro-cli/node_modules/bids-validator/utils/files/readDir.js:264:29)
    at preprocessNode (/usr/local/lib/node_modules/openneuro-cli/node_modules/bids-validator/utils/files/readDir.js:108:16)
    at Object.readDir (/usr/local/lib/node_modules/openneuro-cli/node_modules/bids-validator/utils/files/readDir.js:26:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:30174) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:30174) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mnarayan** [comment] 2019-10-16 01:29
I'm getting a similar error after trying several times. I can confirm the same dataset did not fail bids validation via the web interface. 

```
Adding files to "ds002239"
(node:806) ExperimentalWarning: The http2 module is an experimental API.
bids-validator@1.3.6

(node:806) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'readdir' of undefined
    at getFilesFromFs (/home/groups/xxxx/software/node_modules/bids-validator/utils/files/readDir.js:264:29)
    at preprocessNode (/home/groups/xxxx/software/node_modules/bids-validator/utils/files/readDir.js:108:16)
    at Object.readDir (/home/groups/xxxx/software/node_modules/bids-validator/utils/files/readDir.js:26:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:806) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:806) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nellh** [comment] 2019-10-16 01:34
What version of Node.js are you using? This looks like it could be a Node version issue with recent bids-validator changes.

**Comment by xingyu-liu** [comment] 2019-10-17 02:53
> What version of Node.js are you using? This looks like it could be a Node version issue with recent bids-validator changes.

Hi, I'm the user refered by Franklin. The version of Node.js I'm using is v8.10.0.

**Comment by ckrountree** [comment] 2020-08-05 19:27
This should be fixed once we deploy the updated server side & cli version uploaders.

**Closed as completed by ckrountree** 2020-08-05 19:27 UTC
