### ISSUE TITLE
No email notification for a comment reply

### ISSUE THREAD

**Issue by chrisgorgo** [OpenNeuroOrg/openneuro#936] opened 2018-09-30 22:59 UTC
I never received an email notification for this reply https://openneuro.org/datasets/ds001499/versions/1.1.1#comment-5bb10b4a8c53916ac9cbb8bd. It has also been a while since I got any email notification from OpenNeuro.

**Comment by nellh** [comment] 2018-10-01 16:13
There are emails being sent but I have seen some get created with no destination email, which is probably the source of this issue. Will investigate further.

**Comment by nellh** [comment] 2018-10-01 20:50
Looks like this is caused by a leftover SciTran user API call failing to populate the send address.

**Comment by olgn** [comment] 2018-10-03 21:15
closed via #942

**Closed as completed by olgn** 2018-10-03 21:15 UTC
Labels: bug
