### ISSUE TITLE
change text of FAQ

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#1576] opened 2020-03-23 21:52 UTC
In the openneuro FAQ, there are two instances of the phrase, "period of 36 months counted from first successful analysis of data from more than one participant". Given that openneuro isn't allowing people to run analyses right now, I would think that this limitation isn't very useful. Perhaps it could be replaced with something like, "period of 36 months counted from the first successful snapshot of the dataset."

https://openneuro.org/faq

**Comment by ckrountree** [comment] 2020-06-25 22:22
Addressed in release 3.14.3

**Comment by ckrountree** [comment] 2020-06-25 22:33
Duplicate of #1242

**Closed as completed** 2020-06-26 18:10 UTC
