### ISSUE TITLE
UnhandledPromiseRejectionWarning when uploading datasets using openneuro-cli

### ISSUE THREAD

**Issue by jbwexler** [OpenNeuroOrg/openneuro#843] opened 2018-08-17 17:38 UTC
I receive the following type of error periodically (once or twice a day?) when uploading datasets to openneuro using openneuro-cli:

> Transferring "sub-01/ses-meg/meg/sub-01_ses-meg_task-facerecognition_run-06_meg.fif" - 16% complete (699.7 MB remaining)
Transferring "sub-01/ses-meg/meg/sub-01_ses-meg_task-facerecognition_run-06_meg.fif" - 16% complete (697.6 MB remaining)
(node:23290) UnhandledPromiseRejectionWarning: Error: Network error: Unexpected token < in JSON at position 0
    at new ApolloError (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:124:32)
    at Object.error (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/apollo-client/bundle.umd.js:1102:32)
    at notifySubscription (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:130:18)
    at onNotify (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:161:3)
    at SubscriptionObserver.error (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:220:7)
    at notifySubscription (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:130:18)
    at onNotify (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:161:3)
    at SubscriptionObserver.error (/Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/zen-observable/lib/Observable.js:220:7)
    at /Users/jbwexler/.nvm/versions/node/v10.7.0/lib/node_modules/openneuro-cli/node_modules/apollo-upload-client/lib/main/index.js:156:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:23290) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:23290) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nellh** [comment] 2018-09-07 19:50
This is fixed in 2.2, it was caused by the implicit snapshot failing due to a duplicate tag. The server now decides when to create the 1.0.0 snapshot and won't do so unless it is the first commit and a snapshot does not exist.

**Closed as completed by nellh** 2018-09-07 19:50 UTC
